# Generated by Django 4.1.6 on 2023-02-08 13:40

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(max_length=11, unique=True, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '7XXXXXXXXXX'. Up to 11 digits allowed.", regex='([7]){1}([\\d]){10}')])),
                ('tag', models.CharField(blank=True, max_length=30)),
                ('name', models.CharField(blank=True, max_length=40)),
                ('joined', models.DateTimeField(auto_now_add=True, null=True)),
            ],
            options={
                'ordering': ('id',),
            },
        ),
        migrations.CreateModel(
            name='Maillist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('start', models.DateTimeField(verbose_name='Creation Start date')),
                ('end', models.DateTimeField(verbose_name='Creation End date')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('phone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.client')),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('status', models.BooleanField(default=False)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.client')),
                ('maillist', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='api.maillist')),
            ],
        ),
    ]
